// Builds assets/fonts/fonts-inline.css: the same fonts as data: URIs.
// Only loaded when index.html is opened straight from disk (file://), where
// browsers refuse to load separate font files.  Run: npm run fonts
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const dir = fileURLToPath(new URL('../assets/fonts/', import.meta.url));
const faces = [
  ['Nunito', 'normal', '400 900', 'nunito.woff2'],
  ['Barlow Condensed', 'normal', '600', 'barlow-condensed-600.woff2'],
  ['Barlow Condensed', 'normal', '800', 'barlow-condensed-800.woff2'],
  ['Barlow Condensed', 'italic', '800', 'barlow-condensed-800-italic.woff2'],
];
const css = faces
  .map(([family, style, weight, file]) => `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url(data:font/woff2;base64,${readFileSync(dir + file).toString('base64')}) format('woff2')}`)
  .join('\n');
writeFileSync(dir + 'fonts-inline.css', '/* generated by scripts/embed-fonts.mjs: used only for file:// */\n' + css + '\n');
console.log('wrote assets/fonts/fonts-inline.css');
