// Builds assets/fonts/fonts-inline.css: the same fonts as data: URIs.
// It is only loaded when index.html is opened straight from disk (file://),
// where browsers refuse to load separate font files.  Run: node scripts/embed-fonts.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const dir = fileURLToPath(new URL('../assets/fonts/', import.meta.url));
const faces = [
  ['Fraunces', 'normal', '300 800', 'fraunces.woff2'],
  ['Fraunces', 'italic', '300 600', 'fraunces-italic.woff2'],
  ['Inter', 'normal', '400 700', 'inter.woff2'],
  ['Caveat', 'normal', '500 700', 'caveat.woff2'],
];
const css = faces
  .map(([family, style, weight, file]) => {
    const b64 = readFileSync(dir + file).toString('base64');
    return `@font-face{font-family:'${family}';font-style:${style};font-weight:${weight};font-display:swap;src:url(data:font/woff2;base64,${b64}) format('woff2')}`;
  })
  .join('\n');
writeFileSync(dir + 'fonts-inline.css', '/* generated by scripts/embed-fonts.mjs: used only for file:// */\n' + css + '\n');
console.log('wrote assets/fonts/fonts-inline.css');
